"""enable row-level security for tenant isolation + append-only audit log

Revision ID: 0002
Revises: <SET THIS to the id of your autogenerated initial-schema migration>
Create Date: 2026-08-02

IMPORTANT: this migration assumes the tables already exist (created by
an autogenerated migration from app.models). Run:
    alembic revision --autogenerate -m "initial schema"
against a running Postgres instance first, set that migration's
revision id as the `down_revision` below, then apply this one.

This is the single most important migration in the project: it's what
turns "we filter by tenant_id in application code" (hopeful) into
"Postgres physically cannot return another tenant's rows to this
session" (enforced). See app/db/session.py:set_tenant_context for the
app-side half of this.
"""
from alembic import op

revision = "0002"
down_revision = "REPLACE_WITH_INITIAL_SCHEMA_REVISION_ID"
branch_labels = None
depends_on = None

# Every table that carries a tenant_id column via TenantScopedMixin.
# Keep this list in sync with app/models/mixins.py usage.
TENANT_SCOPED_TABLES = [
    "users",
    "documents",
    "document_chunks",
    "workflow_templates",
    "workflow_instances",
    "approvals",
    "audit_log",
]


def upgrade() -> None:
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        # FORCE means even the table owner is subject to the policy.
        # Without this, a superuser/owner connection silently bypasses
        # RLS -- which defeats the point if your app's DB role happens
        # to own the tables (common in dev setups).
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
            WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
            """
        )

    # Append-only enforcement on audit_log: reject UPDATE and DELETE
    # outright, at the database level, regardless of which role issues
    # them. This is what makes the audit trail trustworthy even if
    # application code has a bug.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_audit_log_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log rows are immutable: % not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_update
        BEFORE UPDATE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_delete
        BEFORE DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_log_mutation")

    for table in TENANT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_{table} ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
